# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 234100db9df11416b3e65c49a8cb0ec27b1344bc07d373318146860466b178dbdf9fff8efbf0898a70258e87a35414277ae03971e245154297793243a0c8395a

test:
  secret_key_base: f3cfce0fab6da13648a1cd4007eb11def71e4989967b5cc1c1403724ccbea7464eac4ca312537353eb70143c8ac5675250b4f209a5f68f58ef092f64256353c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
